// <auto-generated />
using System;
using Accounting.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accounting.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220612132511_Accounting001")]
    partial class Accounting001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accounting.Shared.Models.AccountingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CategoryIncomeExpensesId")
                        .HasColumnType("integer");

                    b.Property<int>("IncomeExpensesId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryIncomeExpensesId");

                    b.HasIndex("IncomeExpensesId");

                    b.ToTable("Accountings");
                });

            modelBuilder.Entity("Accounting.Shared.Models.CategoryIncomeExpenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CategoryIncomeExpense");
                });

            modelBuilder.Entity("Accounting.Shared.Models.IncomeExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryIncomeExpensesId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryIncomeExpensesId");

                    b.ToTable("IncomeExpense");
                });

            modelBuilder.Entity("Accounting.Shared.Models.AccountingModel", b =>
                {
                    b.HasOne("Accounting.Shared.Models.CategoryIncomeExpenses", "CategoryIncomeExpenses")
                        .WithMany("AccountingModels")
                        .HasForeignKey("CategoryIncomeExpensesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accounting.Shared.Models.IncomeExpense", "IncomeExpenses")
                        .WithMany("AccountingModels")
                        .HasForeignKey("IncomeExpensesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryIncomeExpenses");

                    b.Navigation("IncomeExpenses");
                });

            modelBuilder.Entity("Accounting.Shared.Models.IncomeExpense", b =>
                {
                    b.HasOne("Accounting.Shared.Models.CategoryIncomeExpenses", "CategoryIncomeExpenses")
                        .WithMany("IncomeExpenses")
                        .HasForeignKey("CategoryIncomeExpensesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryIncomeExpenses");
                });

            modelBuilder.Entity("Accounting.Shared.Models.CategoryIncomeExpenses", b =>
                {
                    b.Navigation("AccountingModels");

                    b.Navigation("IncomeExpenses");
                });

            modelBuilder.Entity("Accounting.Shared.Models.IncomeExpense", b =>
                {
                    b.Navigation("AccountingModels");
                });
#pragma warning restore 612, 618
        }
    }
}
